[project]
name = "mcp-provider-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.5.2",
    "pydantic[email]>=2.11.5",
]
